services:
  # --- POSTGRESQL: База данных ---
  postgres:
    image: postgres:17-alpine
    container_name: url-shortener-db
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # --- URL SHORTENER ---
  url-shortener:
    build: .
    container_name: url-shortener-app
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - CONFIG_PATH=/app/config/local.yaml
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - HTTP_ADDR=:8082
      - HTTP_SERVER_USER=${HTTP_SERVER_USER}
      - HTTP_SERVER_PASSWORD=${HTTP_SERVER_PASSWORD}
    volumes:
      - ./config:/app/config:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # --- LOKI: Хранилище логов ---
  loki:
    image: grafana/loki:3.2.0
    container_name: url-shortener-loki
    restart: on-failure
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  # --- PROMTAIL: Сборщик логов ---
  promtail:
    image: grafana/promtail:3.2.0
    container_name: url-shortener-promtail
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - app-network
    depends_on:
      - loki

  # --- GRAFANA: Визуализация логов ---
  grafana:
    image: grafana/grafana:11.2.2
    container_name: url-shortener-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=${GRAFANA_ANONYMOUS:-true}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    depends_on:
      - loki

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: